server:
  port: 8080
  servlet:
    context-path: /stockSystem



spring.main.allow-circular-references: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stocks
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostegreSQLDialect
    generate-ddl: true
    hibenate:
      ddl-studio: none
      ddl-auto: update
application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0
